# Uncomment the following lines to define your default indexer and rpc urls
#indexer_url = ""
#rpc_url = ""
#masp_indexer_url = ""
#localnet_enabled = false
indexer_url = "https://namada-indexer.denodes.xyz"
rpc_url = "https://namada-mainnet-rpc.denodes.xyz"
masp_indexer_url = "https://namada-masp-indexer.denodes.xyz"
